{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}-metrics
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
    app.kubernetes.io/metrics: {{ include "helloworld.fullname" . }}-metrics
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "helloworld.selectorLabels" . | nindent 4 }}
{{- end }}